Add parameters for customizing wave size
osrf/vrx pull request #217
Opened 2020-09-26 06:02 UTC by mabelzhang

Added parameters for size and scale of waves.

A larger wave plane is needed for VORC as the terrain covers a larger area.
I guessed this is how to get a bigger wave geometry? It gives me more blue stuff alright. If this isn't the proper way, please let me know how to do it right.

2020-09-29 19:44 UTC, caguero requested changes
The `model.xacro.erb` is generated from `model.xacro.erb`. Could you perhaps move your changes to the `erb` version?

2020-09-30 00:50 UTC, mabelzhang commented
> Could you perhaps move your changes to the `erb` version?
Moved in 825e740
Turns out I didn't actually need to change the size, just the scale. I'm only going by how big the blue area is though, not sure how to judge how big the waves are. Hope that gives the desired effect...

2020-09-30 20:16 UTC, caguero approved these changes

2020-10-01 01:12 UTC, mabelzhang commented
There's a cmake warning and looks like a test failure in the checks. The cmake warning is not related. The test failure just says
```
Unable to find test results for rostest-test_sandisland.xml, test did not run. Expected results in /var/lib/jenkins/workspace/vrx-ci-pr_any_kinetic-xenial-amd64/ws/build/test_results/vrx_gazebo/rostest-test_sandisland.xml
```
Is the test failure expected or should we fix it before merging?

2020-10-01 14:39 UTC, caguero commented
> There's a cmake warning and looks like a test failure in the checks. The cmake warning is not related. The test failure just says
> 
> ```
> Unable to find test results for rostest-test_sandisland.xml, test did not run. Expected results in /var/lib/jenkins/workspace/vrx-ci-pr_any_kinetic-xenial-amd64/ws/build/test_results/vrx_gazebo/rostest-test_sandisland.xml
> ```
> 
> Is the test failure expected or should we fix it before merging?

Let's forget about the error in CI for now if your local tests pass. We'll go back to it after the sprint, I prefer not to be blocked unless there's a critical issue.

2020-10-02 22:41 UTC, mabelzhang commented
All tests pass locally for me.
Actually I don't have permission to merge. Feel free to merge.

2020-10-02 22:48 UTC, merged