Removed 'loop_forever' from perception scoring and perception task world
osrf/vrx pull request #467
Opened 2022-07-04 16:34 UTC by rmvanarse

This PR removes the use of the `loop_forever` parameter in the scoring plugin for the perception task to resolve #457  (the course needs to be fully specified now). It also removes the line setting it to true in `perception_task.world.xacro`.

2022-07-12 15:34 UTC, caguero requested changes
Could you also remove the documentation associated to this parameter in `perception_scoring_plugin.hh`?

2022-07-15 16:34 UTC, rmvanarse commented
Removed the declarations and documentation for `loop_forever` from the header

2022-07-18 15:32 UTC, caguero requested changes

2022-07-18 15:32 UTC, caguero commented on .vscode/c_cpp_properties.json
> +{
Could you remove your `.vscode` files?

2022-07-22 18:31 UTC, caguero approved these changes

2022-07-27 18:19 UTC, merged