Rmvanarse/gazebosim/scoring plugins dev
osrf/vrx pull request #486
Opened 2022-07-21 05:36 UTC by rmvanarse

## Scoring plugin implemented with ignition

**Files added**
- `ScoringPlugin.hh`
- `ScoringPlugin.cc`
- `DummyPlugin.hh`
- `DummyPugin.cc`

The dummy plugins contain skeleton code that can be used for implementing other plugins. The scoring plugins have been structured similarly to the corresponding files in VRX. The main modifications are:
- Functions such as Load() and Update() have been replaced by Configure() and ISystemPreUpdate/ ISystemPostUpdate
- World/ model objects are now entities. Their attributes in Gazebo classic implementations are now components, accessed via the entity component system or a World/Model wrapper to the entities
- ROS publishers and subscribers have been replaced with ignition::transport and ROS messages have been replaced with ignition::msgs.
- Several functions for accessing or setting members have changed (e.g. GetLatitudeReference(), GetHeadingOffset() ). Some functions now require extra arguments such as the ECM or simTime (e.g. UpdateTime() ).
- Changes in data types - The main one is the replacement of ignition::common::Time (deprecated) with std::chrono::duration<double>. 

The following still needs to be done:
- Making time variables consistent in type or unit. Currently std::chrono::duration, std::chrono::steady_clock, ignition::msgs::Time and double are all being used. Additionally, ignition::common::Time, builtin_interfaces::msgs::Time and rclcpp::Time have been removed. 
- Completing the implementation of the PostUpdate function (Accessing the vehicle model and name)
- Code cleanup

2022-08-03 14:23 UTC, caguero commented
Nit: For code consistency with the Gazebo style, could you use the delimiter `//////////////////////////////////////////////////` above each function in the `.cc`. See other files as an example.

2022-08-03 14:58 UTC, caguero commented
Could you provide instructions for testing your PR please?

2022-08-03 14:58 UTC, caguero requested changes

2022-08-03 14:58 UTC, caguero commented on vrx_ign/CMakeLists.txt
> +find_package(ignition-physics4 REQUIRED)
This should be `physics5` as this is the version in Gazebo Fortress. See [this repository](https://github.com/gazebo-tooling/gazebodistro/blob/master/collection-fortress.yaml) for all the library versions in each Gazebo distribution. Change the next line too.

2022-08-03 14:58 UTC, caguero commented on vrx_ign/src/ScoringPlugin.hh
> +        std::chrono::duration<double> simTime;
Remove?

2022-08-03 14:58 UTC, caguero commented on vrx_ign/src/ScoringPlugin.hh
> +        private: std::vector<std::chrono::duration<double> > collisionTimestamps;
Nit: Remove the space between the two `>`.

2022-08-03 14:58 UTC, caguero commented on vrx_ign/src/ScoringPlugin.hh
> +        ignition::msgs::Any taskMsgName, taskMsgState,
Nit: Following the Gazebo convention, don't group member variables. Instead, declare them in separate lines.

2022-08-03 14:58 UTC, caguero commented on vrx_ign/src/ScoringPlugin.hh
> +        protected: std::unique_ptr<ignition::transport::Node::Publisher> taskPub;
Nit: Split the lines that go beyond 80 characters.

2022-08-03 14:58 UTC, caguero commented on vrx_ign/src/ScoringPlugin.hh
> +
Nit: remove empty line.

2022-08-03 14:58 UTC, caguero commented on vrx_ign/src/ScoringPlugin.cc
> +    ignition::msgs::Time readyTimeMsg, runningTimeMsg;
Nit: Split into two separate lines.

2022-08-03 14:58 UTC, caguero commented on vrx_ign/src/ScoringPlugin.cc
> +    auto running_sec = std::chrono::duration_cast<std::chrono::seconds>(this->runningTime);
I recommend to create a helper function to set the time, as it appears many times.

2022-08-03 14:58 UTC, caguero commented on vrx_ign/src/ScoringPlugin.cc
> +
The code in VRX verifies the `VRX_DEBUG` environment variable to set `this->debug`. Should we add it?

2022-08-03 14:59 UTC, caguero requested changes

2022-08-03 14:59 UTC, caguero commented on vrx_ign/CMakeLists.txt
> +find_package(rclcpp REQUIRED)
Do we need this?

2022-08-09 14:30 UTC, caguero commented
@rmvanarse , could you please fix the conflicts?

2022-08-09 20:27 UTC, caguero commented
@rmvanarse , in order to unblock this pull request, I suggest:

* Document all the issues, ToDos and questions in a separate issue.
* Polish the part that's working and wrap it up.
* We'll create a separate PR to address the outstanding issues of this plugin.

Does it work for you?

2022-08-09 21:19 UTC, rmvanarse commented
Sure! Will do it 👍🏼

2022-08-24 18:19 UTC, closed without merging

2022-08-24 18:20 UTC, caguero commented
Replaced with #501 .